// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AdminRegionRepository is an autogenerated mock type for the AdminRegionRepository type
type AdminRegionRepository struct {
	mock.Mock
}

// Add provides a mock function with no fields
func (_m *AdminRegionRepository) Add() {
	_m.Called()
}

// ListCitiesInRegion provides a mock function with no fields
func (_m *AdminRegionRepository) ListCitiesInRegion() {
	_m.Called()
}

// ListRetionsAndCitiesInCoutry provides a mock function with no fields
func (_m *AdminRegionRepository) ListRetionsAndCitiesInCoutry() {
	_m.Called()
}

// ListRetionsInCoutry provides a mock function with no fields
func (_m *AdminRegionRepository) ListRetionsInCoutry() {
	_m.Called()
}

// Update provides a mock function with no fields
func (_m *AdminRegionRepository) Update() {
	_m.Called()
}

// NewAdminRegionRepository creates a new instance of AdminRegionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminRegionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminRegionRepository {
	mock := &AdminRegionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
