name: Go Unit Tests with Mockery

on:
  push:
    branches:
      - main
      - feature_**
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.18.0" # Adjust to your Go version

      - name: Install Mockery
        run: go install github.com/vektra/mockery/v2@latest

      - name: Generate Mocks
        run: mockery --all --recursive

      - name: Get dependencies
        run: go mod tidy
        working-directory: .

      - name: Run unit tests
        run: go test -v ./...
        working-directory: .

      - name: Run coverage (optional)
        run: go test -v -coverprofile=coverage.out ./...
        working-directory: .

      # - name: Upload coverage to Codecov (optional)
      #   uses: codecov/codecov-action@v3
      #   with:
      #     files: coverage.out
      #     fail_ci_if_error: true
      #     verbose: true
