// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AdminRegionApp is an autogenerated mock type for the AdminRegionApp type
type AdminRegionApp struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx
func (_m *AdminRegionApp) Add(ctx context.Context) {
	_m.Called(ctx)
}

// Query provides a mock function with no fields
func (_m *AdminRegionApp) Query() {
	_m.Called()
}

// Update provides a mock function with no fields
func (_m *AdminRegionApp) Update() {
	_m.Called()
}

// NewAdminRegionApp creates a new instance of AdminRegionApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminRegionApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminRegionApp {
	mock := &AdminRegionApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
