// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// AdminRegionHandler is an autogenerated mock type for the AdminRegionHandler type
type AdminRegionHandler struct {
	mock.Mock
}

// AddCity provides a mock function with given fields: c
func (_m *AdminRegionHandler) AddCity(c *gin.Context) {
	_m.Called(c)
}

// AddRegion provides a mock function with given fields: c
func (_m *AdminRegionHandler) AddRegion(c *gin.Context) {
	_m.Called(c)
}

// DeleteCity provides a mock function with given fields: c
func (_m *AdminRegionHandler) DeleteCity(c *gin.Context) {
	_m.Called(c)
}

// DeleteRegion provides a mock function with given fields: c
func (_m *AdminRegionHandler) DeleteRegion(c *gin.Context) {
	_m.Called(c)
}

// GetCityInRegion provides a mock function with given fields: c
func (_m *AdminRegionHandler) GetCityInRegion(c *gin.Context) {
	_m.Called(c)
}

// ListCityInCountryByRegion provides a mock function with given fields: c
func (_m *AdminRegionHandler) ListCityInCountryByRegion(c *gin.Context) {
	_m.Called(c)
}

// ListCityInRegion provides a mock function with given fields: c
func (_m *AdminRegionHandler) ListCityInRegion(c *gin.Context) {
	_m.Called(c)
}

// ListRegion provides a mock function with given fields: c
func (_m *AdminRegionHandler) ListRegion(c *gin.Context) {
	_m.Called(c)
}

// ListRegionInCountry provides a mock function with given fields: c
func (_m *AdminRegionHandler) ListRegionInCountry(c *gin.Context) {
	_m.Called(c)
}

// UpdateRegion provides a mock function with given fields: c
func (_m *AdminRegionHandler) UpdateRegion(c *gin.Context) {
	_m.Called(c)
}

// NewAdminRegionHandler creates a new instance of AdminRegionHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminRegionHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminRegionHandler {
	mock := &AdminRegionHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
