name: Integration Tests

on:
  workflow_dispatch:

jobs:
  integration-tests:
    name: Run Integration tests
    runs-on: ubuntu-latest

    steps:
        - name: Install Docker Compose
          run: |
            sudo apt-get update
            sudo apt-get install -y docker-compose-plugin        
        - name: Check Docker and Docker Compose
          run: |
            docker --version
            docker-compose --version

