name: Integration Tests

on:
  workflow_dispatch:

jobs:
  integration-tests:
    name: Run Integration tests
    runs-on: ubuntu-latest

    steps:
        - name: Check Docker and Docker Compose
          run: |
            docker --version
            docker-compose --version

