services:
  db_test:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "${MYSQL_PORT}:3306"
    env_file:
      - "../../.env.test"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --silent"]
      timeout: 30s
      retries: 20
      start_period: 30s
  baseline:
    image: flyway/flyway
    environment:
      - FLYWAY_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
      - FLYWAY_USER=${MYSQL_ROOT_USER}
      - FLYWAY_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true
    command: baseline
    volumes:
      - ../../migrations:/flyway/sql
    depends_on:
      db_test:
        condition: service_healthy
  migrate:
    image: flyway/flyway
    environment:
      - FLYWAY_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false
      - FLYWAY_USER=${MYSQL_ROOT_USER}
      - FLYWAY_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - FLYWAY_VALIDATE_MIGRATION_NAMING=true
    command: migrate
    volumes:
      - ../../migrations:/flyway/sql
    depends_on:
      - baseline
  app_test:
    build:
      context: ../../
      dockerfile: ./deployments/docker/Dockerfile_test
    restart: unless-stopped
    volumes:
      - ../../:/opt/cps
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - "../../.env.test"
    depends_on:
      - db_test
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 18081:8080
    depends_on:
      db_test:
        condition: service_healthy
